baseurl: ""
url: ""
lang: en
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/news/page/:num"
manual:
  pages:
    - name: index
      desc: Manual Index
    - name: 01-signin
      desc: Manage Microsoft Accounts
    - name: 02-profiles
      desc: Manage Launcher Profiles
    - name: 03-gamever
      desc: Select the Game Version
    - name: 04-ram
      desc: Change RAM Allocation
    - name: 05-logs
      desc: Collect Launcher Logs
    - name: 06-installmg
      desc: Manage a Minecraft Profile