name: Generate Sitemap

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          sitemap-format: 'xml'  # Choose 'xml' or 'txt'
          output-file: 'sitemap.xml'  # Output file name
